[features]
seeds = true

[programs.localnet]
decidooor = "C7EcdBmywF3p1CwMJntzFN81PNyaf92yKZbkseoPck8D"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/cindy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
